blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/juanezamudio/.github/discussions
    about: For questions or discussions, please use GitHub Discussions instead of opening an issue.
